name: Build OS Content
on:
  push:
    branches:
      - master
  workflow_dispatch: {}
  workflow_run:
    workflows: [Build Base OS (periodic)]
    types:
      - completed

env:
  REGISTRY_USER: aleskandrox
  IMAGE_REGISTRY: quay.io
  IMAGE_NAME: fedora-kinoite
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build-os-content:
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Build and Push Fedora Kinoite (OS Content)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set versioned tag
        id: versioned-tag
        run: |
          VERSIONED_TAG=$(date -u --iso-8601=minutes | sed 's/://g;s/+.*$//')-${GITHUB_SHA}
          echo "VERSIONED_TAG=${VERSIONED_TAG}" >> $GITHUB_OUTPUT
      - name: Build OS content
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}
          tags: rawhide-layered rawhide-layered-${{ steps.versioned-tag.outputs.VERSIONED_TAG }}
          containerfiles: |
            ./Containerfile
      - name: Push to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:rawhide-layered ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:rawhide-layered-${{ steps.versioned-tag.outputs.VERSIONED_TAG }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

